export const FETCHING_BOARDS = 'FETCHING_BOARDS';
export const BOARDS_FETCHED_SUCCESSFULLY = 'BOARDS_FETCHED_SUCCESSFULLY';
export const FETCHING_BOARD = 'FETCHING_BOARD';
export const BOARD_FETCHED_SUCCESSFULLY = 'FETCHED_BOARD_SUCCESSFULLY';
export const FETCHING_CARD = 'FETCHING_CARD';
export const CARD_FETCHED_SUCCESSFULLY = 'FETCHED_CARD_SUCCESSFULLY';
